#pragma once

#include <set>
#include <random>
#include <limits>
#include <vector>
#include <string>
#include <bitset>
#include <memory>
#include <sstream>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <functional>
#include <map>
#include <unordered_map>
#include <filesystem>
#include <typeinfo>
#include <typeindex>